### PR TITLE
Standalone sync + client-only mod pushing

### PR DESCRIPTION
**Pull request by rheimus**
Updated with capability to run serversync.jar and have it sync files without starting Minecraft.

Added GUI, basic but provides necessary feedback.

### CODE REVIEW

**Comment by superzanti** [comment]
Rheimus, it looks like you've done a lot of work on this. I have been busy with my Master's degree and haven't even touched serversync in a year.

I'm going to test your version out and if everything works, would you like to become a developer?

**Comment by rheimus** [comment]
Sure, Would love to.

Have fun with the degree!

**Comment by superzanti** [comment]
Would you  mind crating a small readme with the changes so I can effectively test it?

**Comment by rheimus** [comment]
Sure, ill put together a list of the changes from the original idea.
Shouldn't be too long.

**Comment by rheimus** [comment]
### Basic Functionality:
1. Install serversync on server and client as normal
2. Run serversync{ver}.jar from mods folder (or create shortcut)

### Client Mods
1. Create folder in base directory of the server called "clientmods"
2. Set push_client_mods to true in config

### Config
1. Include list is for white listing config files to sync, add file name including extension (not full path) e.g. _myconfig.cfg_
2. Ignore list is for ignoring mods in the sync/deletion processes, add file name including extension (not full path) e.g. _mymod.jar_

**Comment by superzanti** [comment]
You are now a collaborator on this project since I no longer can work on it.

**Comment by rheimus** [comment]
Awsome :dancers: , shall try my best to keep it up to date

**Pull request merged**
